# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ebsnakliyat2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.12.2'
  # Pods for ebsnakliyat2

  target 'ebsnakliyat2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ebsnakliyat2UITests' do
    # Pods for testing
  end

end
